### ISSUE TITLE
Undeclared model object keys default to undefined instead of empty string

### ISSUE THREAD

**Issue by jreviews** [alpinejs/alpine#77]
Take a look at the following examples:

Alpine.js - https://codepen.io/jreviews/pen/NWPMVMz

Vue.js - https://codepen.io/jreviews/pen/wvBjbNX

In Alpine.js, undeclared model object keys default to undefined, while in Vue.js they default to an empty string. Is it possible to have a similar behavior as Vue.js? It's ok to add the model keys to the object if there's a handful, but if there are dozens or hundreds it gets more complicated.

**Comment by goodallt** [comment]
You could also explicitly define the object attribute as an empty string. It would look something like this: 
```<form x-data="{ formData: { name: '' } }">```

**Comment by jreviews** [comment]
@goodallt Thanks, that's what I mentioned before:

> It's ok to add the model keys to the object if there's a handful, but if there are dozens or hundreds it gets more complicated.

I believe it would be an improvement not to explicitly have to declare every input in the object. I am thinking of very large forms here.

**Comment by calebporzio** [comment]
Hmmm... I guess I don't have a strong opinion on this either way. I would be open to a PR, if the implementation was simple enough.

**Comment by calebporzio** [comment]
Should be fixed in the latest release- thanks for the PR!

**Comment by simarlab** [comment]
It's really closed this issue? I still receive undefined instead of an empty string.
Let me know, and thanks a lot for your great work!

**Comment by Henriquex25** [comment]
I still receive undefined instead of an empty string.

**Comment by SimoTod** [comment]
This bug was raised for v2, v3 has a different implementation and, currently, it returns the real value.
I think you can work around that with something like `<span x-text="myobj.myprop ?? ''">`
